name: example-environment
channels:
  - conda-forge
  - osgeo
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - flopy
  - gdal
  - pandas
